name: Deployment in DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@dev
      - run: rsync -az ${{secrets.DEV_PATH_SOURCE}} ${{secrets.DEV_PATH_TO}}